Update Expo SDK to version 57 (#53)
* Update Expo SDK to version 56

* build(deps): Upgrade deps to match new SDK version

* build(deps): Remove react-navigation

`expo-router` no longer depends on `react-navigation`.
All imports of `react-navigation` were changed using the codemod 
`sdk-56-expo-router-react-navigation-replace`

* refactor(app.config): use type-safe config plugins

* build(deps): Update Expo SDK to version 57

* build(deps): Upgrade deps to match new SDK version

This includes a [fix](https://github.com/expo/expo/pull/49211) 
for `matchContents` not working correctly (included in expo@57.0.16).

* fix(settings): broken layout

The buttons to switch mode were not visible.

* fix(local-source-settings-view): crash due to IllegalStateException

This fixes a crash that was caused by using `matchContents` on the same
axis as a scrollable child (in this case the LazyColumn).

* fix(more-settings-view): crash due to IllegalStateException

Same issue as previous commit.

* fix(jetpack-compose): handle new color format

Jetpack Compose colors are now formatted as #rrggbbaa just as usual
colors instead of #aarrggbb.

* fix(list-item): wrong text color when disabled

* refactor(services-source): use built-in TopTabs

Expo Router already includes the material top tabs as a component, so no
need to create it ourselves.

* refactor(services-source): add manual type definitions to TopTabs

Something about the types broke when updating Expo Router, so we
manually add the types

* fix(local-source-settings-view): icons overflowing container

* fix(services-view-item): icons overflowing container

* fix(local-source-settings-view): services overflowing beyond navbar

* chore(i18n): update translations

* fix(generate-schema): ignore brand action

* fix(use-color-scheme.web): synchronous useState call in useEffect

Just removed the file, since it's not needed.

* fix(use-theme): first argument needs to be an inline function expression

* fix(generate-schema): node types missing

* fix(typecheck): run `expo customize tsconfig.json` before tsc

This generates the file expo-env.d.ts which is required for typescript
to check the types correctly.
Without it, we get this error:
```
src/constants/theme.ts:1:8 - error TS2882: Cannot find module or type declarations for side-effect import of '@/global.css'.
```

* ci(check-code): only check that src/locales didn't change