fix(typecheck): run `expo customize tsconfig.json` before tsc
This generates the file expo-env.d.ts which is required for typescript
to check the types correctly.
Without it, we get this error:
```
src/constants/theme.ts:1:8 - error TS2882: Cannot find module or type declarations for side-effect import of '@/global.css'.
```